blog/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail')
]

first/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home')
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=25)
    subtitle = models.CharField(max_length=40, blank=True, null=True)
    tags = models.CharField(max_length=40, blank=True, null=True)
    slug = models.SlugField(null=True,
                            allow_unicode=True, unique=True)
    author = models.CharField(max_length=20, blank=True, null=True)
    brief = models.TextField(max_length=185)
    article = models.TextField(max_length=9000000, blank=True, null=True)
    imag = models.ImageField(upload_to='blog_image/', blank=True, null=True)
    date_added = models.DateField(default=timezone.now, blank=True, null=True)

    def __str__(self):
        return self.title

    def taglist(self):
        return self.tags.split('-')

home/models.py
from django.db import models
from django.core import validators
import re

# Create your models here.


def validator(self):
    if re.match(r"(\d{1,3}),(\d{1,3}),(\d{1,3})", self):
        return True
    else:
        raise validators.ValidationError(message="Please,enter correct rgb color. Example: '255,255,255' for white.")


class Home(models.Model):
    showing_blog_button = models.BooleanField(
        default=True, blank=True, null=True)
    button_color = models.CharField(
        validators=[validator], max_length=128, blank=True, null=True)
    e_mail = models.CharField(
        validators=[validators.EmailValidator(message="Please, enter corresponding email address")], max_length=128, blank=True, null=True)
    background_image_url1 = models.URLField(validators=[validators.URLValidator(
        message="Please, enter correct address")], max_length=250, blank=True, null=True)
    background_image_url2 = models.URLField(validators=[validators.URLValidator(
        message="Please, enter correct address")], max_length=250, blank=True, null=True)
    background_image_url3 = models.URLField(validators=[validators.URLValidator(
        message="Please, enter correct address")], max_length=250, blank=True, null=True)
    logo = models.ImageField(blank=True, null=True)
    About_link = models.URLField(
        validators=[validators.URLValidator], max_length=200, blank=True, null=True)
    Contact_link = models.URLField(
        validators=[validators.URLValidator], max_length=200, blank=True, null=True)
    title = models.CharField(max_length=50, null=True)
    Slogan = models.CharField(max_length=250, null=True)
    website_icon = models.ImageField(upload_to="ico/", blank=True, null=True)

    def Title(self):
        return self.title.upper()

blog/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from .models import Post

# Create your views here.


def index(request):
    posts = Post.objects.all()
    return render(request, 'blog.html', {'posts': posts})


def detail(request, slug):
    post = Post.objects.get(slug=slug)
    posts = Post.objects.all()
    return render(request, 'article.html', {'post': post, 'posts': posts})

first/views.py
# from django.shortcuts import render


# def home(request):
#     return render(request, 'home.html')

home/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from .models import Home

# Create your views here.


def home(request):
    home = Home.objects.get(id=1)
    return render(request, 'home.html', {'home': home})

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>

<html>

<head>
    <title>Django-example-blog</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'/>
    <link rel="stylesheet" href="{% static 'style.css' %}" />

        {% block content %} {% endblock content %}
</body>

</html>

templates/blog.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Example-Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:300,400,700"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="https://darabi.website/static/blog.css" />
  </head>
  <body>
    <!-- partial:index.partial.html -->
{% for post in posts %}
{% if forloop.counter|divisibleby:2  %}

    <div class="blog-card">
      <div class="meta">
        <div
          class="photo"
          style="background-image: url({{ post.imag.url }})"
        ></div>
        <ul class="details">
          <li class="author">
            <a href="#">{{ post.author }}</a>
          </li>
          <li class="date">{{ post.date_added }}</li>
          <li class="tags">
            <ul>
              {% for t in post.taglist %}

              <li><a href="#">{{ t }}</a></li>
              
              {% endfor %}
            </ul>
          </li>
        </ul>
      </div>
      <div class="description">
        <h1>{{ post.title }}</h1>
        <h2>{{ post.subtitle }}</h2>
        <p>{{ post.brief }}</p>
        <p class="read-more">
          <a href="{% url 'blog:detail' post.slug %}">Read More</a>
        </p>
      </div>
    </div>
{% else %}
    <div class="blog-card alt">
      <div class="meta">
        <div
          class="photo"
          style="background-image: url({{ post.imag.url }})"
        ></div>
        <ul class="details">
          <li class="author"><a href="#">{{ post.author }}</a></li>
          <li class="date">{{ post.date_added }}</li>
          <li class="tags">
            <ul>
              {% for t in post.taglist %}

              <li><a href="#">{{ t }}</a></li>
              
              {% endfor %}
            
            
              <!-- <li><a href="#">Code</a></li>
              <li><a href="#">HTML</a></li>
              <li><a href="#">CSS</a></li> -->
            </ul>
          </li>
        </ul>
      </div>
      <div class="description">
        <h1>{{ post.title }}</h1>
        <h2>{{ post.subtitle }}</h2>
        <p>{{ post.brief }}</p>
        <p class="read-more">
          <a href="{% url 'blog:detail' post.slug %}">Read More</a>
        </p>
      </div>
    </div>
{% endif %}
{% endfor %}
    <!-- partial -->
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <link rel="icon" href="{{ home.website_icon.url }}"/>
    <style>
    body {
        overflow: hidden;
    }
            .container-fluid.main{
                position: relative; /* To make the navbar positions relative to this container */
                padding: 0;
              }
              
              .navbar-default {
                background-image: none;
                background-color: transparent; /* Make the menu become transparent */
                border-radius: 0px;
                border: 0;
                box-shadow: none;
                padding: 10px;
                position: absolute; /* Make the menu out of the document flow so it can placed anywhere without disturbing other widgets */
                top: 0;
                left: 0;
                right: 0;
                z-index: 10; /* If you delete this line, your menu link won't be clicked because it is behind the background. Applying this code bring the menu in front of the background */
              }
              
              .navbar-default .navbar-brand {
                font-family: Verdana;
                color: #ffffff;
                font-size: 20px;
              }
              
              .navbar-default .navbar-brand:hover,
              .navbar-default .navbar-brand:focus {
                color: #ffffff;
                background-color: transparent;
              }
              
              .navbar-default .navbar-nav > li > a {
                color: #ffffff;
              }
              
              .navbar-default .navbar-nav > li > a:hover,
              .navbar-default .navbar-nav > li > a:focus {
                color: #ffffff;
                background-color: transparent;
              }
              
              .navbar-default .navbar-toggle {
                border-color: transparent;
              }
              
              .navbar-default .navbar-toggle:hover {
                background-color: transparent;
              }
              
              .navbar-default .navbar-toggle:focus {
                background-color: transparent;
              }
              
              .navbar-default .navbar-toggle .icon-bar {
                background-color: #ffffff;
              }
              
              .carousel .background {
                background-position: center center;
                background-size: 100% 100%;
                background-repeat: no-repeat;
                height: 700px;
              }
              
              @media (max-width:991px) {
                .carousel .background {
                  background-size: cover; /* To make the background image looks good */
                }
              }
              
              .carousel .background.a {
                background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url({{ home.background_image_url1 }});
              }
              
              .carousel .background.b {
                background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url({{ home.background_image_url2 }});
              }
              
              .carousel .background.c {
                background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url({{ home.background_image_url3 }});
              }
              
              .carousel-fade .carousel-inner .item {
                opacity: 0;
                transition: opacity 0.5s; /* The 0.5s describes the duration to make the opacity from 0 to 1 */
              }
              
              .carousel-fade .carousel-inner .active {
                opacity: 1;
              }
              
              /* CSS Hack to trigger GPU for smooth transition */
              @media all and (transform-3d),
              (-webkit-transform-3d) {
                .carousel-fade .carousel-inner > .item.next,
                .carousel-fade .carousel-inner > .item.active.right {
                  opacity: 0;
                  -webkit-transform: translate3d(0, 0, 0);
                  transform: translate3d(0, 0, 0);
                }
                .carousel-fade .carousel-inner > .item.prev,
                .carousel-fade .carousel-inner > .item.active.left {
                  opacity: 0;
                  -webkit-transform: translate3d(0, 0, 0);
                  transform: translate3d(0, 0, 0);
                }
                .carousel-fade .carousel-inner > .item.next.left,
                .carousel-fade .carousel-inner > .item.prev.right,
                .carousel-fade .carousel-inner > .item.active {
                  opacity: 1;
                  -webkit-transform: translate3d(0, 0, 0);
                  transform: translate3d(0, 0, 0);
                }
              }
              /* CSS Hack to trigger GPU for smooth transition */
              
              .covertext {
                position: absolute; /* To make the div to be place anywhere. It is out of the document flow */
                top: 200px; /* The distance between the div with the top of document */
                left: 0px; /* Make the div full width */
                right: 0px; /* Make the div full width */
              }
              
              .title {
                font-family: Verdana;
                font-weight: 600;
                font-size: 60px;
                color: #ffffff;
                text-align: center;
              }
              
              .subtitle {
                font-family: Verdana;
                font-size: 23px;
                color: #ffffff;
                text-align: center;
              }
              
              .explore {
                text-align: center;
                margin-top: 10px;
              }
              
              .explore .btn-lg,
              .explore .btn-lg:hover {
                border-radius: 30px;
                padding: 15px 25px;
                font-size: 22px;
                background-image: none;
                background-color: rgb({{ home.button_color }});
                border-color: rgb({{ home.button_color }});
                color: #ffffff;
              }
              
              .btn,
              .btn:hover {
                border-radius: 0px;
                background-image: none;
                background-color: #FF4000;
                border-color: #FF4000;
                color: #ffffff;
                margin-bottom: 20px;
                box-shadow: none;
                outline: none;
              }
              
              .btn:focus,
              .btn:active:focus,
              .btn.active:focus,
              .btn.focus,
              .btn:active.focus,
              .btn.active.focus {
                color: #ffffff;
                outline: none;
              }
    </style>
    </head>
    <body>
<!-- partial:index.partial.html -->
<div class="container-fluid main">

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand" href="#" style="margin-top: 0px;padding-top: 5px;"><img width="50px" height="50px" src="{{ home.logo.url }}"/></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="{{ home.About_link }}">About</a></li>
          <li><a href="{{ home.Contact_link }}">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="myCarousel" class="carousel carousel-fade slide" data-ride="carousel" data-interval="3000">
    <div class="carousel-inner" role="listbox">
      <div class="item active background a"></div>
      <div class="item background b"></div>
      <div class="item background c"></div>
    </div>
  </div>
  
  <div class="covertext">
    <div class="col-lg-10" style="float:none; margin:0 auto;">
      <h1 class="title">{{ home.Title }}</h1>
      <h3 class="subtitle">{{ home.Slogan }}</h3>
    </div>
{% if home.showing_blog_button %}
    <div class="col-xs-12 explore">
      <a href="{% url 'blog:index' %}"><button type="button" class="btn btn-lg explorebtn">My Blog</button></a>
    </div>
{% endif %}
  </div>
  
</div>
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js'></script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'></script>
<script>
$('.carousel').carousel({
    pause: "false" 
});
</script>

{% endblock  %}